config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'set_role' => 'home#set_role'
  resources :events do 
    resources :tasks
  end
  get '/events/:event_id/tasks/:id/set_role' => 'tasks#set_role', as: :set_task_role
  
  root to: "home#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :event
  has_many :user_tasks
  has_many :users, :through => :user_tasks
  alias_method :participants, :users
  validates :title, :presence => :true
  validates :description, :presence => :true
  validates :start_time, :presence => :true
  validates :end_time, :presence => :true
  validates :workers_required, :presence => :true
  
  def self.total_tasks
    self.all.count
  end

  def positions_available
    self.workers_required - self.users.all.count
  end

  def event_task_styling
    self.users.all.count == self.workers_required ? "class=text-success" : "class=text-danger"
  end

end

app/controllers/task_controller.rb
class TasksController < ApplicationController

  def show
    @task = task
    @users = @task.users
  end

  def new
    @task = Task.new
  end

  def create
    set_event
    @task = @event.tasks.build(task_params)
    if !@task.save
      render 'new'
    else
      redirect_to event_path(@event)
    end
  end

  def destroy
    set_event
    task.destroy
    redirect_to event_path(@event)
  end

  def edit
    @task = task
  end

  def update
    set_event
    if current_user.member?
      sign_up
    elsif organizer_permissions?
      task.update(task_params)
      redirect_to event_path(@event)
    end
  end

  def sign_up
    task.users << current_user unless task.users.include?(current_user)
    set_event
    flash[:notice] = "Successfully added you to this task."
    redirect_to event_path(@event)
  end

  def task
    Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :start_time, :end_time, :workers_required, :id)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
    @task = Task.find(params[:id])
    @users = @task.users
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @task}
    end
  end

  def new
    @task = Task.new
  end

  def create
    set_event
    @task = @event.tasks.build(task_params)
    if !@task.save
      render 'new'
    else
      redirect_to event_task_path(@event, @task)
    end
  end

  def set_role
    @task = task
  end

  def destroy
    set_event
    task.destroy
    redirect_to event_path(@event)
  end

  def edit
    @task = task
  end

  def update
    set_event
    if current_user.member?
      sign_up
    elsif organizer_permissions?
      task.update(task_params)
      redirect_to event_path(@event)
    end
  end

  def sign_up
    @task = task
    set_event
    @usertask = task.user_tasks.find_or_create_by(user_id: current_user.id, task_id: @task.id)
    @usertask.update(task_role: params['user']['task_role'])
    flash[:notice] = "Successfully added you to this task."
    redirect_to event_task_path(@event, @task)
  end

  def task
    Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :start_time, :end_time, :workers_required, :id)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  
  
end

app/views/tasks/_edit.html.erb
<%= form_for @task, url: {action: "update", method: "post"} do |f| %>
  <%= f.label :title %> <br>
  <%= f.text_field :title %> <br>
  <%= f.label :description %> <br>
  <%= f.text_area :description %> <br>
  <div class="input-group bootstrap-timepicker timepicker">
      <%= f.label :start_time %> <br>
      <%= f.text_field :start_time, "class" => "input-small" %> <br>
      <%= f.label :end_time %> <br>
      <%= f.text_field :end_time, "class" => "input-small" %> <br>
      <script type="text/javascript">
        $('#task_start_time').timepicker({
          template: 'dropdown',
          defaultTime: false
        });
        $('#task_end_time').timepicker({
          template: 'dropdown',
          defaultTime: false
        });
      </script>
  </div> <br>
  <%= f.label :workers_required, "Workers/Volunteers Required" %> <br>
  <%= f.number_field :workers_required %> <br><br>
  <%= f.submit %>
<% end %>

app/views/tasks/_new.html.erb
<%= form_for @task, url: {action: "create", method: "post"} do |f| %>
  <%= f.label :title %> <br>
  <%= f.text_field :title %> <br>
  <%= f.label :description %> <br>
  <%= f.text_area :description %> <br>
  <div class="input-group bootstrap-timepicker timepicker">
      <%= f.label :start_time %> <br>
      <%= f.text_field :start_time, "class" => "input-small" %> <br>
      <%= f.label :end_time %> <br>
      <%= f.text_field :end_time, "class" => "input-small" %> <br>
      <script type="text/javascript">
        $('#task_start_time').timepicker({
          template: 'dropdown',
          defaultTime: false
        });
        $('#task_end_time').timepicker({
          template: 'dropdown',
          defaultTime: false
        });
      </script>
  </div> <br>
  <%= f.label :workers_required, "Workers/Volunteers Required" %> <br>
  <%= f.number_field :workers_required %> <br><br>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'edit' %>

app/views/tasks/new.html.erb
<div class="text-center"> 
  <h1>Add Task</h1>
</div> <hr>
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h4>
      <%= pluralize(@task.errors.count, "error") %>
      prohibited this event from being saved:
    </h4>
 
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'new' %>

app/views/tasks/set_role.html.erb
<h1>Set Preferred Role</h1>
<h4>Notice: Your role may be subject to change</h4>
<%= form_for(@task, url: event_task_path, :method => :patch) do |f| %>

<div class="field">
    <input id="task_role_supervisor" name="user[task_role]" type="radio" value="supervisor">
    <label for="task_role_supervisor">Supervisor</label>
    <input id="task_role_worker" name="user[task_role]" type="radio" value="worker">
    <label for="task_role_worker">Worker</label><hr>
</div>

<div class="actions">
    <%= f.submit "Sign Up For Task" %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<div class="text-center">
  <h1><%= @task.title %></h1> 
  <% if organizer_permissions? %>
    <%= link_to("Delete Task", event_task_path, :method => :delete, data: {:confirm => "Are you sure you want to  delete this task?"}) %> |
    <%= link_to("Edit Task", edit_event_task_path) if organizer_permissions? %> 
  <% elsif current_user.member? && @task.positions_available > 0 %>
    <button><%= link_to("Sign Up For This Task", set_task_role_path) %></button>
  <% else %>
    <strong class="text-success"><h3>All Positions Taken</h3></strong>
  <% end %>
</div> <hr>
<strong>Workers Required:</strong> <%= @task.workers_required %> <br> <br>
<strong>Description:</strong> <%= @task.description %> <br /> <br>
<strong>Time Slot:</strong> <%= @task.start_time %> - <%= @task.end_time %> <br /> <br>
<strong <%=task_styling%>>Participants: <%= @task.users.all.count %> / <%= @task.workers_required %> </strong> <br />
<% @users.each do |user| %>
  <%= user.email %>  <strong><%= "- " + user_task_role(user).capitalize if user_task_role(user) == "supervisor" %></strong><br>
<% end %>

<hr>


  