config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'set_role' => 'home#set_role'
  resources :events do 
    resources :tasks
  end
  get '/events/:event_id/tasks/:id/set_role' => 'tasks#set_role', as: :set_task_role
  
  root to: "home#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :tasks
  belongs_to :user
  alias_method :organizer, :user
  accepts_nested_attributes_for :tasks
  validates :title, :presence => :true
  validates :description, :presence => :true
  validates :date, :presence => :true
  validates :start_time, :presence => :true
  validates :end_time, :presence => :true

  def task_attributes=(task)
    self.tasks = Task.find_or_create_by(title: task.title)
    self.tasks.update(task)
  end

  def all_positions_filled?
    self.tasks.map {|task|
    if task.workers_required == task.users.all.count
      task.id
    end}.compact.size == task_ids.size
  end


  # def task_ids
  #   self.tasks.map do |task|
  #     task.id 
  #   end
  # end

  def positions_remaining(task_ids)
    task_ids.map { |id|
    task = Task.find(id);
    task.workers_required - task.users.all.count}.sum
  end

  def participants
    collect = []
    if self.tasks
      self.tasks.each do |task|
        task.users.each do |user|
          collect << user
        end
      end
    end
    collect.uniq
  end

    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_many :user_tasks
  has_many :tasks, :through => :user_tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  enum role: [:admin, :organizer, :member]
  validates :role, presence: true, if: Proc.new { |a| a.provider.nil? }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all 
  end

  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @event}
    end
  end

  def new
    @event = Event.new
    @event.tasks.build
  end

  def create
    if empty_task_params_field?
      @event = current_user.events.build(event_params)
      if @event.save 
        redirect_to(event_path(@event))
      else
        @event.tasks.build
        render('new')
      end
    else
      @event = current_user.events.build(event_with_task_params)
      @event.save ? redirect_to(event_path(@event)) : render('new')
    end 
  end

  def edit
    set_event
  end

  def update
    set_event
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    set_event
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :start_time, :end_time)
  end

  def event_with_task_params
    params.require(:event).permit(:title, :description, :date, :start_time, :end_time, tasks_attributes: [:title, :description, :start_time, :end_time, :workers_required, :id])
  end

  def empty_task_params_field?
    param = params["event"]["tasks_attributes"]["0"]
    param["title"].empty? && param["description"].empty? && param["start_time"].empty? && param["end_time"].empty? && param["workers_required"].empty?
  end

  def set_event
    @event = Event.find(params[:id])
  end


end

app/views/events/_edit.html.erb
<%= form_for @event, url: {action: "update", method: "post"} do |f| %>
    <%= f.label :name %> <br>
    <%= f.text_field :title %> <br>
    <%= f.label :description %> <br>
    <%= f.text_area :description %> <br>
    <%= f.label :date %> <br>
    <%= f.text_field :date, "data-provide" => 'datepicker' %> <br>
    <div class="input-group bootstrap-timepicker timepicker">
      <%= f.label :start_time %> <br>
      <%= f.text_field :start_time, "class" => "input-small" %> <br>
      <%= f.label :end_time %> <br>
      <%= f.text_field :end_time, "class" => "input-small" %> <br>
      <script type="text/javascript">
            $('#event_start_time').timepicker({
              template: 'dropdown',
              defaultTime: false
            });
            $('#event_end_time').timepicker({
              template: 'dropdown',
              defaultTime: false
            });
        </script>
    </div> <br>
    <%= f.submit %>
  <% end %>

app/views/events/_new.html.erb
<%= form_for @event, url: {action: "create", method: "post"} do |f| %>
    <%= f.label :name %> <br>
    <%= f.text_field :title %> <br>
    <%= f.label :description %> <br>
    <%= f.text_area :description %> <br>
    <%= f.label :date %> <br>
    <%= f.text_field :date, "data-provide" => 'datepicker' %> <br>
  <div class="input-group bootstrap-timepicker timepicker">
    <%= f.label :start_time %> <br>
    <%= f.text_field :start_time, "class" => "input-small" %> <br>
    <%= f.label :end_time %> <br>
    <%= f.text_field :end_time, "class" => "input-small" %> <br>
    <script type="text/javascript">
          $('#event_start_time').timepicker({
            template: 'dropdown',
            defaultTime: false
          });
          $('#event_end_time').timepicker({
            template: 'dropdown',
            defaultTime: false
          });
      </script>
  </div>
<h4>-------------------------</h4>
  <h4>Create A Task (optional)</h4>
    <%= f.fields_for :tasks do |task| %>
      <%= task.label :title %> <br>
      <%= task.text_field :title %> <br>
      <%= task.label :description %> <br>
      <%= task.text_area :description %> <br>
    <div class="input-group bootstrap-timepicker timepicker">
      <%= task.label :start_time %> <br>
      <%= task.text_field :start_time, "class" => "input-small" %> <br>
      <%= task.label :end_time %> <br>
      <%= task.text_field :end_time, "class" => "input-small" %> <br>
      <script type="text/javascript">
        $('#event_tasks_attributes_0_start_time').timepicker({
          template: 'dropdown',
          defaultTime: false
        });
        $('#event_tasks_attributes_0_end_time').timepicker({
          template: 'dropdown',
          defaultTime: false
        });
      </script>
    </div> <br>
      <%= task.label :workers_required, "Workers/Volunteers Required" %> <br>
      <%= task.number_field :workers_required %> <br><br>
    <% end %> <hr>
    <%= f.submit "Create Event" %>
  <% end %>

app/views/events/edit.html.erb
<div class="text-center"> 
  <h1>Edit Event</h1>
</div> <hr>
<% if logged_in? %>
  <%= render 'edit' %>
<% else %>
  <p>Please login to edit Events</p>
<% end %>

app/views/events/index.html.erb
<div class='text-center'>
  <h1 class="title">Events</h1>
  <div class="page-nav">
    <% if organizer_permissions? %>
      <%= link_to("Create New Event", new_event_path, :id => 'new-event')%>
    <% end %>
  </div>
</div> <hr>

<div class="event-show" style="display: none"></div>
<div class="task-show" style="display: none"></div>
<div class="event-index">
  
  <% @events.each do |event| %>
    <h4><%= link_to(event.title, event_path(event), :'data-id' => event.id, :'data-title' => event.title, :class => 'js-showEvent') %> - (<%= event.date %>) 
    <% if event.all_positions_filled? %>
     
    <text class="text-success">All Positions Filled</text></h4>
    <% else %>
      <text class="text-danger"><%= event.positions_remaining(event.task_ids) %> Position(s) To Be  Filled</text></h3>
    <% end %>
  
    <p><%= truncate event.description.squish, :length => 150, :separator => /\w/, :omission => "... " %></p>
  
  
    <hr>
  <% end %>
</div>
<div class="scripts"></div>

app/views/events/new.html.erb
<div class='text-center'>
  <h1>Create Event</h1>
</div> <hr>
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h4>
      <%= pluralize(@event.errors.count, "error") %>
      prohibited this event from being saved:
    </h4>
 
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if logged_in? %>
  <%= render 'new' %>
<% else %>
  <p>Please login to create Events</p>
<% end %>   

app/views/events/show.html.erb
<div class='text-center'>

  <h1 class="title"><%= @event.title %></h1>

  <div class="window-nav">
    <% if organizer_permissions? %>
      <%= link_to("Edit Event", edit_event_path(@event), :id => 'edit_event') %> |
      <%= link_to("Add Task", new_event_task_path(@event), :id => 'add_event') %> |
      <%= link_to("Delete Event", event_path(@event), :id => 'delete_event', :method => 'delete', data: {:confirm => "Are  you sure you want to do delete this event?"}) %>
    <% end %>
  </div>

</div><hr>

  <strong class='text-warning'>Organized By: </strong> <text ><%= @event.organizer.name %></text><br>
  <strong>Date: </strong><%= @event.date %><br>
  <strong>From: </strong><%= @event.start_time %> to <%= @event.end_time %> <hr>

  <strong>Description: </strong><%= @event.description %> <hr>
  <strong>Tasks:</strong> <br>
  <% @event.tasks.each do |task| %>
    <%= link_to task.title, event_task_path(@event, task) %> - <strong <%= task.event_task_styling %>><%= task.positions_available %> position(s) remaining </strong> <br>
  <% end %> <hr>

  <strong>Participants:</strong>
  <% @event.participants.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
  <hr>